trigger: none
pool: functionapp
stages:
 - stage: 
   displayName: Build Stage
   jobs:
   - job: 
     displayName: Terraform Install
     steps:
     - task: TerraformInstaller@1
       displayName: Terraform Install
       inputs:
         terraformVersion: 'latest'
     - task: TerraformTask@5

       displayName: terraform init
       inputs:
         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(System.DefaultWorkingDirectory)/ENV/DEV'
         backendServiceArm: 'myself'
         backendAzureRmStorageAccountName: 'pehlastg_1761306100929'
         backendAzureRmContainerName: 'pehlacont'
         backendAzureRmKey: 'key.tfstate'
     - task: TerraformTask@5
       displayName: terraform validate
       inputs:
         provider: 'azurerm'
         command: 'validate'
         workingDirectory: '$(System.DefaultWorkingDirectory)ENV/DEV'
     - task: TerraformTask@5
       displayName: terraform Plan
       inputs:
         provider: 'azurerm'
         command: 'plan'
         workingDirectory: '$(System.DefaultWorkingDirectory)ENV/DEV'
         environmentServiceNameAzureRM: 'myself'